version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        volumes:
          - ./configDB/initdb:/docker-entrypoint-initdb.d
          - ./dataDB/mysql:/var/lib/mysql
          - ./logsDB/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: usuario
            MYSQL_DATABASE: museobd
            MYSQL_USER: usuario
            MYSQL_PASSWORD: usuario
        ports:
            - "3307:3306"
    web: 
        build: ./
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
           - ./:/museo
        ports: 
          - "3001:3000"
        depends_on:
          - db
        links:
          - db
        environment:
          DB_USER: usuario  
          DB_NAME: museobd
          DB_PASSWORD: usuario
          DB_HOST: db
    phpmyadmin:
        image: phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: usuario
            MYSQL_PASSWORD: usuario
            MYSQL_ROOT_PASSWORD: usuario
        volumes:
          - ./configPMA/pma.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

